# Site settings
title: Cheeky Giraffe
email: bex@cheekygiraffe.com
description: Cheeky little site for a cheeky little Giraffe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cheekygiraffe.com" # the base hostname & protocol for your site
twitter_username: jekyllrb

# Build settings
markdown: kramdown
exclude: [s3_website.yml,README.md,CNAME]
